AY2425S1-CS2113-W13-3/tp

- src/main/java/command/Command.java
- src/main/java/command/EchoCommand.java
- src/main/java/parser/Parser.java
- src/test/java/parser/ParserTest.java
Fixes #7 
Created a Parser class for parsing user input in the application.
The parser parses a command and returns a Command object corresponding to the command parsed.
For all input, the parser returns an EchoCommand (which echoes the user input.)
> Implement a parser that parses commands

- src/main/java/seedu/manager/command/MenuCommand.java
Created MenuCommand class.
The menu lists all possible commands that can be performed, accompanied with a short description of what each command does.
Fixes #28
> Solve issue: Implement a “menu” command to list out the set of possible actions that can be taken

- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/parser/ParserTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
Updated parser class and tests to handle menu command.
The program is now able to display menu message when "menu" command is entered.
Fixes #29
> Solve issue: Add support for the “menu” command to parser

- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/LectureEvent.java
Considering that different types of event makes it difficult to do commands like adding, delete it for v1.0
If we wanna an inheritance in the future, discuss for the next iteration.
> Make Event not abstract. Delete the subclass LectureEvent of Event. 

- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/parser/Parser.java
> Add support for the 'add' command to the parser.

- src/main/java/seedu/manager/command/ListCommand.java
- src/main/java/seedu/manager/parser/Parser.java
> Add support for the 'list' command to the parser

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/command/Command.java
- src/main/java/seedu/manager/command/CommandOutput.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/ui/Ui.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/runtest.sh
in order to make it easier to do edition to the event list and more OOP.
> Rebuild the structure based on the previous one

- src/main/java/seedu/manager/command/ListCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/test/java/seedu/manager/command/ListCommandTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
> Implement a "list" command that allows the user to see existing events.

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/command/ListCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/parser/ParserTest.java
Add an AddCommand to take in event as a parameter for now which adds to the array list in EventList class
Fixes #18 
Fixes #42 
Fixes #44
> Add AddCommand to add events to the event list 

- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/AddCommandTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
Add functionality to add participants to each event. Update parser to support new functionality.
Fixes #1 
Fixes #2 
Fixes #10
> Implement function to add participants to events

- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/command/RemoveCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/AddCommandTest.java
- src/test/java/seedu/manager/command/RemoveCommandTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
Add functionality to remove participants from each event. Update parser to support new functionality.
Fixes #4 
Fixes #5 
Fixes #12
> Implement function to remove participants from events

- src/main/java/seedu/manager/command/ViewCommand.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/parser/Parser.java
The "view" command now checks if there is a matching event, and returns a message if this is so.
> Add error handling for the "view" command

- src/test/java/seedu/manager/command/AddCommandTest.java
- src/test/java/seedu/manager/command/RemoveCommandTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
Reverts AY2425S1-CS2113-W13-3/tp#76
> Revert "Add JUnit test for addEvent and removeEvent"

- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/command/SortCommand.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/SortCommandTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
> Sort events by name

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/storage/Storage.java
- src/main/java/seedu/manager/ui/Ui.java
- src/test/java/seedu/manager/storage/StorageTest.java
- text-ui-test/EXPECTED.TXT
Add functionality to save current events locally to a text file - "events.txt"
Fixes #50
> Implement Storage class

- docs/DeveloperGuide.md
The draft is for the task of week 10.
> Edit DG: list feature (draft only, diagrams will be added later)

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/exception/DuplicateDataException.java
- src/test/java/seedu/manager/command/AddCommandTest.java
This PR adds error handling for duplicate entries for the event list and participant lists of events.
Fixes #105.
Fixes #106.
> Fix duplicate entry bugs

- src/main/java/seedu/manager/command/FindCommand.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/FindCommandTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
- text-ui-test/EXPECTED.TXT
Add FindCommand class to find all participants in an event with a certain name
Update parser to support
Modify JUnit tests
Fixes #113 
Fixes #114
> Add Find command

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/command/CopyCommand.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/item/Participant.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/AddCommandTest.java
- src/test/java/seedu/manager/command/CopyCommandTest.java
- src/test/java/seedu/manager/command/FindCommandTest.java
- src/test/java/seedu/manager/command/MarkParticipantCommandTest.java
- src/test/java/seedu/manager/command/RemoveCommandTest.java
- src/test/java/seedu/manager/command/ViewCommandTest.java
- src/test/java/seedu/manager/item/ParticipantTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
Implement contact info of participant into the different classes
Fixes #96
> Add contact info of participants

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/command/CopyCommand.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/item/Participant.java
- src/main/java/seedu/manager/parser/Parser.java
- src/main/java/seedu/manager/storage/Storage.java
- src/test/java/seedu/manager/command/AddCommandTest.java
- src/test/java/seedu/manager/command/CopyCommandTest.java
- src/test/java/seedu/manager/command/FindCommandTest.java
- src/test/java/seedu/manager/command/MarkParticipantCommandTest.java
- src/test/java/seedu/manager/command/RemoveCommandTest.java
- src/test/java/seedu/manager/command/ViewCommandTest.java
- src/test/java/seedu/manager/item/ParticipantTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
Edited storage parsing implementation
> Modify Storage parsing implementation

- docs/UserGuide.md
- src/main/java/seedu/manager/command/EditEventCommand.java
- src/main/java/seedu/manager/command/EditParticipantCommand.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/EditEventCommandTest.java
- src/test/java/seedu/manager/command/EditParticipantCommandTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/events.csv
- text-ui-test/input.txt
> edit event command implementation

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/command/EditEventCommand.java
- src/main/java/seedu/manager/command/EditItemCommand.java
- src/main/java/seedu/manager/command/EditParticipantCommand.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/item/Item.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/EditEventCommandTest.java
- src/test/java/seedu/manager/command/EditItemCommandTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
> edit the item

- src/main/java/seedu/manager/command/ViewCommand.java
This PR adds Javadoc headers for the getParticipants and getItems methods in View command.
> Add Javadocs for methods in ViewCommand

- build.gradle
- src/main/java/seedu/manager/command/MarkEventCommand.java
- src/main/java/seedu/manager/command/MarkItemCommand.java
- src/main/java/seedu/manager/command/MarkParticipantCommand.java
- src/main/java/seedu/manager/parser/Parser.java
This PR consolidates the error handling code for index out of bound, date-time and priority errors.
> Reduce duplicate code in parser error handling

- docs/DeveloperGuide.md
> Change DG appendix titles to align with requirements

- src/main/java/seedu/manager/command/CopyCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/item/Item.java
This PR fixes the copy command bug (copying the reference instead of the list over) that was not completely fixed in #172.
> Fix copy command

- src/main/java/seedu/manager/Main.java
- src/main/java/seedu/manager/storage/FileParser.java
- src/main/java/seedu/manager/storage/Storage.java
- src/main/java/seedu/manager/ui/Ui.java
- src/test/java/seedu/manager/storage/StorageTest.java
- text-ui-test/EXPECTED.TXT
I change data.csv to data.txt file
Fixes #178 
Fixes #203
> Add ability to parse other languages

- src/main/java/seedu/manager/storage/Storage.java
PR #235 did not update the filename for the isValidFilename assertion, so the program could not run. This PR fixes that.
> Fix incorrect filename for data.txt

- src/main/java/seedu/manager/command/FilterCommand.java
- src/main/java/seedu/manager/parser/Parser.java
Fixes #194 
Fixes #196 
Fixes #198 
Fixes #211  
Fixes #216
> Update all regex and parse command methods

- src/main/java/seedu/manager/event/EventList.java
> Update sort by name method

- docs/UserGuide.md
- src/main/java/seedu/manager/command/MenuCommand.java
- text-ui-test/EXPECTED.TXT
This PR comprises updates to the DG in line with bug reports, for consistency, and to reflect the program's functionality.
It excludes amendments to the `edit` command and to the storage functionality.
Fixes #176.
Fixes #177.
Fixes #179.
Fixes #199.
> Update user guide in line with PE-D bug reports

- src/main/java/seedu/manager/command/AddCommand.java
- src/main/java/seedu/manager/command/CopyCommand.java
- src/main/java/seedu/manager/command/EditParticipantCommand.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/event/Event.java
- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/item/Participant.java
- src/main/java/seedu/manager/parser/Parser.java
- src/main/java/seedu/manager/storage/FileParser.java
- src/main/java/seedu/manager/storage/Storage.java
- src/test/java/seedu/manager/command/AddCommandTest.java
- src/test/java/seedu/manager/command/CopyCommandTest.java
- src/test/java/seedu/manager/command/EditEventCommandTest.java
- src/test/java/seedu/manager/command/EditParticipantCommandTest.java
- src/test/java/seedu/manager/command/FindCommandTest.java
- src/test/java/seedu/manager/command/MarkParticipantCommandTest.java
- src/test/java/seedu/manager/command/RemoveCommandTest.java
- src/test/java/seedu/manager/command/ViewCommandTest.java
- src/test/java/seedu/manager/item/ParticipantTest.java
- src/test/java/seedu/manager/storage/StorageTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
Fixes #200
Fixes #204
Fixes #209
> Remove participant phone number

- docs/UserGuide.md
- src/main/java/seedu/manager/command/CopyCommand.java
Fixes the errors and UG regressions from the merging of #242.
> Edit user guide in line with phone number removal

- src/main/java/seedu/manager/command/FilterCommand.java
- src/main/java/seedu/manager/command/MenuCommand.java
- src/main/java/seedu/manager/parser/Parser.java
- src/test/java/seedu/manager/command/AddCommandTest.java
- src/test/java/seedu/manager/command/ViewCommandTest.java
- src/test/java/seedu/manager/parser/ParserIntegrationTest.java
- src/test/java/seedu/manager/parser/ParserTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
Fixes #248 
Fixes #208 
Fixes #185 
Fixes #182
> Manual Testing Bugs fixes

- src/main/java/seedu/manager/event/EventList.java
- src/main/java/seedu/manager/parser/Parser.java
This PR comprises the refactoring of methods in the Parser to reduce deep nesting and duplicate code.
> Improve code quality for Parser
